name: Android Tests
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
         api-level: 23
         target: google_apis
         arch: x86_64
         script: ./gradlew connectedCheck