name: Android Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
         api-level: 23
         target: google_apis
         arch: x86_64
         script: ./gradlew connectedCheck
      - name: Build
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}